<?xml version="1.0" encoding="utf-8"?>
<Database Class="DataClassesDataContext" Serialization="Unidirectional" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="" Member="HeuristicLabUsers">
    <Type Name="HeuristicLabUser">
      <Column Name="id" Member="ID" Storage="_id" Type="System.Int64" IsReadOnly="true" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Modifier="Virtual" Type="System.String" IsReadOnly="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" CanBeNull="false" />
      <Column Name="LastPasswordChangedDate" Modifier="Virtual" Type="System.DateTime" IsReadOnly="true" CanBeNull="false" />
      <Column Name="PasswordQuestion" Modifier="Virtual" Type="System.String" IsReadOnly="true" CanBeNull="false" />
      <Column Name="PasswordAnswer" Type="System.String" CanBeNull="false" />
      <Column Name="Email" Modifier="Virtual" Type="System.String" CanBeNull="false" />
      <Column Name="Comment" Modifier="Virtual" Type="System.String" CanBeNull="false" />
      <Column Name="Locked" Type="System.Boolean" CanBeNull="false" />
      <Association Name="HeuristicLabUser_HeuristicLabUserRole" Member="HeuristicLabUserRoles" Storage="_HeuristicLabUserRole" ThisKey="ID" OtherKey="HeuristicLabUserID" Type="HeuristicLabUserRole" />
    </Type>
  </Table>
  <Table Name="" Member="HeuristicLabRole">
    <Type Name="HeuristicLabRole">
      <Column Name="ID" Type="System.Int64" IsReadOnly="true" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="roleName" Member="RoleName" Storage="_roleName" Type="System.String" CanBeNull="false" />
      <Column Name="parentRoleID" Member="ParentRoleID" Storage="_parentRoleID" Type="System.Int64" CanBeNull="true" />
      <Column Name="IsPermission" Type="System.Boolean" CanBeNull="false" />
      <Association Name="HeuristicLabRole_HeuristicLabRole" Member="HeuristicLabRoleChilds" Storage="_HeuristicLabRole2" ThisKey="ID" OtherKey="ParentRoleID" Type="HeuristicLabRole" />
      <Association Name="HeuristicLabRole_HeuristicLabUserRole" Member="HeuristicLabUserRoles" Storage="_HeuristicLabUserRole" ThisKey="ID" OtherKey="HeuristicLabRoleID" Type="HeuristicLabUserRole" />
      <Association Name="HeuristicLabRole_HeuristicLabRole" Member="HeuristicLabRoleParent" Storage="_HeuristicLabRole1" ThisKey="ParentRoleID" OtherKey="ID" Type="HeuristicLabRole" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="" Member="HeuristicLabUserRole">
    <Type Name="HeuristicLabUserRole">
      <Column Name="ID" Type="System.Int64" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HeuristicLabUserID" Type="System.Int64" CanBeNull="false" />
      <Column Name="HeuristicLabRoleID" Type="System.Int64" CanBeNull="false" />
      <Association Name="HeuristicLabUser_HeuristicLabUserRole" Member="HeuristicLabUser" ThisKey="HeuristicLabUserID" OtherKey="ID" Type="HeuristicLabUser" IsForeignKey="true" />
      <Association Name="HeuristicLabRole_HeuristicLabUserRole" Member="HeuristicLabRole" Storage="_HeuristicLabAbstractRole" ThisKey="HeuristicLabRoleID" OtherKey="ID" Type="HeuristicLabRole" IsForeignKey="true" />
    </Type>
  </Table>
</Database>