set configuration=Release

copy ..\..\..\sources\HeuristicLab.AdvancedOptimizationFrontend\bin\%configuration%\HeuristicLab.AdvancedOptimizationFrontend.dll .
copy ..\..\..\sources\HeuristicLab.AdvancedOptimizationFrontend\bin\%configuration%\HeuristicLab.AdvancedOptimizationFrontend.xml .
copy ..\..\..\sources\HeuristicLab.AdvancedOptimizationFrontend\bin\%configuration%\WeifenLuo.WinFormsUI.Docking.dll .
copy ..\..\..\sources\HeuristicLab.BitVector\bin\%configuration%\HeuristicLab.BitVector.dll .
copy ..\..\..\sources\HeuristicLab.BitVector\bin\%configuration%\HeuristicLab.BitVector.xml .
copy ..\..\..\sources\HeuristicLab.Charting\bin\%configuration%\HeuristicLab.Charting.dll .
copy ..\..\..\sources\HeuristicLab.Charting\bin\%configuration%\HeuristicLab.Charting.xml .
copy ..\..\..\sources\HeuristicLab.Charting.Data\bin\%configuration%\HeuristicLab.Charting.Data.dll .
copy ..\..\..\sources\HeuristicLab.Charting.Data\bin\%configuration%\HeuristicLab.Charting.Data.xml .
copy ..\..\..\sources\HeuristicLab.Constraints\bin\%configuration%\HeuristicLab.Constraints.dll .
copy ..\..\..\sources\HeuristicLab.Constraints\bin\%configuration%\HeuristicLab.Constraints.xml .
copy ..\..\..\sources\HeuristicLab.Core\bin\%configuration%\HeuristicLab.Core.dll .
copy ..\..\..\sources\HeuristicLab.Core\bin\%configuration%\HeuristicLab.Core.xml .
copy ..\..\..\sources\HeuristicLab.Data\bin\%configuration%\HeuristicLab.Data.dll .
copy ..\..\..\sources\HeuristicLab.Data\bin\%configuration%\HeuristicLab.Data.xml .
copy ..\..\..\sources\HeuristicLab.DataAnalysis\bin\%configuration%\HeuristicLab.DataAnalysis.dll .
copy ..\..\..\sources\HeuristicLab.DataAnalysis\bin\%configuration%\HeuristicLab.DataAnalysis.xml .
copy ..\..\..\sources\HeuristicLab.DistributedEngine\bin\%configuration%\HeuristicLab.DistributedEngine.dll .
copy ..\..\..\sources\HeuristicLab.DistributedEngine\bin\%configuration%\HeuristicLab.DistributedEngine.xml .
copy ..\..\..\sources\HeuristicLab.ES\bin\%configuration%\HeuristicLab.ES.dll .
copy ..\..\..\sources\HeuristicLab.ES\bin\%configuration%\HeuristicLab.ES.xml .
copy ..\..\..\sources\HeuristicLab.Evolutionary\bin\%configuration%\HeuristicLab.Evolutionary.dll .
copy ..\..\..\sources\HeuristicLab.Evolutionary\bin\%configuration%\HeuristicLab.Evolutionary.xml .
copy ..\..\..\sources\HeuristicLab.Functions\bin\%configuration%\HeuristicLab.Functions.dll .
copy ..\..\..\sources\HeuristicLab.Functions\bin\%configuration%\HeuristicLab.Functions.xml .
copy ..\..\..\sources\HeuristicLab.Grid\bin\%configuration%\HeuristicLab.Grid.dll .
copy ..\..\..\sources\HeuristicLab.Grid\bin\%configuration%\HeuristicLab.Grid.xml .
copy ..\..\..\sources\HeuristicLab.Logging\bin\%configuration%\HeuristicLab.Logging.dll .
copy ..\..\..\sources\HeuristicLab.Logging\bin\%configuration%\HeuristicLab.Logging.xml .
copy ..\..\..\sources\HeuristicLab.Operators\bin\%configuration%\HeuristicLab.Operators.dll .
copy ..\..\..\sources\HeuristicLab.Operators\bin\%configuration%\HeuristicLab.Operators.xml .
copy ..\..\..\sources\HeuristicLab.Operators.Programmable\bin\%configuration%\HeuristicLab.Operators.Programmable.dll .
copy ..\..\..\sources\HeuristicLab.Operators.Programmable\bin\%configuration%\HeuristicLab.Operators.Programmable.xml .
copy ..\..\..\sources\HeuristicLab.OptimizationFrontend\bin\%configuration%\HeuristicLab.OptimizationFrontend.dll .
copy ..\..\..\sources\HeuristicLab.OptimizationFrontend\bin\%configuration%\HeuristicLab.OptimizationFrontend.xml .
copy ..\..\..\sources\HeuristicLab.Permutation\bin\%configuration%\HeuristicLab.Permutation.dll .
copy ..\..\..\sources\HeuristicLab.Permutation\bin\%configuration%\HeuristicLab.Permutation.xml .
copy ..\..\..\sources\HeuristicLab.PluginInfrastructure\bin\%configuration%\HeuristicLab.PluginInfrastructure.dll .
copy ..\..\..\sources\HeuristicLab.PluginInfrastructure\bin\%configuration%\HeuristicLab.PluginInfrastructure.xml .
copy ..\..\..\sources\HeuristicLab.PluginInfrastructure.GUI\bin\%configuration%\HeuristicLab.PluginInfrastructure.GUI.dll .
copy ..\..\..\sources\HeuristicLab.PluginInfrastructure.GUI\bin\%configuration%\HeuristicLab.PluginInfrastructure.GUI.xml .
copy ..\..\..\sources\HeuristicLab.PluginInfrastructure.GUI\bin\%configuration%\ICSharpCode.SharpZipLib.dll .
copy ..\..\..\sources\HeuristicLab.Random\bin\%configuration%\HeuristicLab.Random.dll .
copy ..\..\..\sources\HeuristicLab.Random\bin\%configuration%\HeuristicLab.Random.xml .
copy ..\..\..\sources\HeuristicLab.RealVector\bin\%configuration%\HeuristicLab.RealVector.dll .
copy ..\..\..\sources\HeuristicLab.RealVector\bin\%configuration%\HeuristicLab.RealVector.xml .
copy ..\..\..\sources\HeuristicLab.Routing.TSP\bin\%configuration%\HeuristicLab.Routing.TSP.dll .
copy ..\..\..\sources\HeuristicLab.Routing.TSP\bin\%configuration%\HeuristicLab.Routing.TSP.xml .
copy ..\..\..\sources\HeuristicLab.Scheduling.JSSP\bin\%configuration%\HeuristicLab.Scheduling.JSSP.dll .
copy ..\..\..\sources\HeuristicLab.Scheduling.JSSP\bin\%configuration%\HeuristicLab.Scheduling.JSSP.xml .
copy ..\..\..\sources\HeuristicLab.Selection\bin\%configuration%\HeuristicLab.Selection.dll .
copy ..\..\..\sources\HeuristicLab.Selection\bin\%configuration%\HeuristicLab.Selection.xml .
copy ..\..\..\sources\HeuristicLab.Selection.OffspringSelection\bin\%configuration%\HeuristicLab.Selection.OffspringSelection.dll .
copy ..\..\..\sources\HeuristicLab.Selection.OffspringSelection\bin\%configuration%\HeuristicLab.Selection.OffspringSelection.xml .
copy ..\..\..\sources\HeuristicLab.SequentialEngine\bin\%configuration%\HeuristicLab.SequentialEngine.dll .
copy ..\..\..\sources\HeuristicLab.SequentialEngine\bin\%configuration%\HeuristicLab.SequentialEngine.xml .
copy ..\..\..\sources\HeuristicLab.SGA\bin\%configuration%\HeuristicLab.SGA.dll .
copy ..\..\..\sources\HeuristicLab.SGA\bin\%configuration%\HeuristicLab.SGA.xml .
copy ..\..\..\sources\HeuristicLab.SQLite\bin\%configuration%\HeuristicLab.SQLite.dll .
copy ..\..\..\sources\HeuristicLab.SQLite\bin\%configuration%\HeuristicLab.SQLite.xml .
copy ..\..\..\sources\HeuristicLab.StructureIdentification\bin\%configuration%\HeuristicLab.StructureIdentification.dll .
copy ..\..\..\sources\HeuristicLab.StructureIdentification\bin\%configuration%\HeuristicLab.StructureIdentification.xml .
copy ..\..\..\sources\HeuristicLab.TestFunctions\bin\%configuration%\HeuristicLab.TestFunctions.dll .
copy ..\..\..\sources\HeuristicLab.TestFunctions\bin\%configuration%\HeuristicLab.TestFunctions.xml .
copy ..\..\..\sources\HeuristicLab.ThreadParallelEngine\bin\%configuration%\HeuristicLab.ThreadParallelEngine.dll .
copy ..\..\..\sources\HeuristicLab.ThreadParallelEngine\bin\%configuration%\HeuristicLab.ThreadParallelEngine.xml .

pause