//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeuristicLab.Hive.Client.Console.ClientWCFService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusCommons", Namespace="http://schemas.datacontract.org/2004/07/HeuristicLab.Hive.Client.Core.ClientConso" +
        "leService")]
    [System.SerializableAttribute()]
    public partial class StatusCommons : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid ClientGuidk__BackingFieldField;
        
        private System.DateTime ConnectedSincek__BackingFieldField;
        
        private int JobsAbortedk__BackingFieldField;
        
        private int JobsDonek__BackingFieldField;
        
        private int JobsFetchedk__BackingFieldField;
        
        private HeuristicLab.Hive.Client.Console.ClientWCFService.JobStatus[] Jobsk__BackingFieldField;
        
        private HeuristicLab.Hive.Client.Console.ClientWCFService.StatusCommons.ClientStatusEnum Statusk__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ClientGuid>k__BackingField", IsRequired=true)]
        public System.Guid ClientGuidk__BackingField {
            get {
                return this.ClientGuidk__BackingFieldField;
            }
            set {
                if ((this.ClientGuidk__BackingFieldField.Equals(value) != true)) {
                    this.ClientGuidk__BackingFieldField = value;
                    this.RaisePropertyChanged("ClientGuidk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ConnectedSince>k__BackingField", IsRequired=true)]
        public System.DateTime ConnectedSincek__BackingField {
            get {
                return this.ConnectedSincek__BackingFieldField;
            }
            set {
                if ((this.ConnectedSincek__BackingFieldField.Equals(value) != true)) {
                    this.ConnectedSincek__BackingFieldField = value;
                    this.RaisePropertyChanged("ConnectedSincek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<JobsAborted>k__BackingField", IsRequired=true)]
        public int JobsAbortedk__BackingField {
            get {
                return this.JobsAbortedk__BackingFieldField;
            }
            set {
                if ((this.JobsAbortedk__BackingFieldField.Equals(value) != true)) {
                    this.JobsAbortedk__BackingFieldField = value;
                    this.RaisePropertyChanged("JobsAbortedk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<JobsDone>k__BackingField", IsRequired=true)]
        public int JobsDonek__BackingField {
            get {
                return this.JobsDonek__BackingFieldField;
            }
            set {
                if ((this.JobsDonek__BackingFieldField.Equals(value) != true)) {
                    this.JobsDonek__BackingFieldField = value;
                    this.RaisePropertyChanged("JobsDonek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<JobsFetched>k__BackingField", IsRequired=true)]
        public int JobsFetchedk__BackingField {
            get {
                return this.JobsFetchedk__BackingFieldField;
            }
            set {
                if ((this.JobsFetchedk__BackingFieldField.Equals(value) != true)) {
                    this.JobsFetchedk__BackingFieldField = value;
                    this.RaisePropertyChanged("JobsFetchedk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Jobs>k__BackingField", IsRequired=true)]
        public HeuristicLab.Hive.Client.Console.ClientWCFService.JobStatus[] Jobsk__BackingField {
            get {
                return this.Jobsk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Jobsk__BackingFieldField, value) != true)) {
                    this.Jobsk__BackingFieldField = value;
                    this.RaisePropertyChanged("Jobsk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Status>k__BackingField", IsRequired=true)]
        public HeuristicLab.Hive.Client.Console.ClientWCFService.StatusCommons.ClientStatusEnum Statusk__BackingField {
            get {
                return this.Statusk__BackingFieldField;
            }
            set {
                if ((this.Statusk__BackingFieldField.Equals(value) != true)) {
                    this.Statusk__BackingFieldField = value;
                    this.RaisePropertyChanged("Statusk__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="StatusCommons.ClientStatusEnum", Namespace="http://schemas.datacontract.org/2004/07/HeuristicLab.Hive.Client.Core.ClientConso" +
            "leService")]
        public enum ClientStatusEnum : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Connected = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Disconnected = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            ConnInterrupted = 2,
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JobStatus", Namespace="http://schemas.datacontract.org/2004/07/HeuristicLab.Hive.Client.Core.ClientConso" +
        "leService")]
    [System.SerializableAttribute()]
    public partial class JobStatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long JobIdk__BackingFieldField;
        
        private double Progressk__BackingFieldField;
        
        private System.DateTime Sincek__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<JobId>k__BackingField", IsRequired=true)]
        public long JobIdk__BackingField {
            get {
                return this.JobIdk__BackingFieldField;
            }
            set {
                if ((this.JobIdk__BackingFieldField.Equals(value) != true)) {
                    this.JobIdk__BackingFieldField = value;
                    this.RaisePropertyChanged("JobIdk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Progress>k__BackingField", IsRequired=true)]
        public double Progressk__BackingField {
            get {
                return this.Progressk__BackingFieldField;
            }
            set {
                if ((this.Progressk__BackingFieldField.Equals(value) != true)) {
                    this.Progressk__BackingFieldField = value;
                    this.RaisePropertyChanged("Progressk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Since>k__BackingField", IsRequired=true)]
        public System.DateTime Sincek__BackingField {
            get {
                return this.Sincek__BackingFieldField;
            }
            set {
                if ((this.Sincek__BackingFieldField.Equals(value) != true)) {
                    this.Sincek__BackingFieldField = value;
                    this.RaisePropertyChanged("Sincek__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConnectionContainer", Namespace="http://schemas.datacontract.org/2004/07/HeuristicLab.Hive.Client.Core.ClientConso" +
        "leService")]
    [System.SerializableAttribute()]
    public partial class ConnectionContainer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string IPAdressk__BackingFieldField;
        
        private int Portk__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<IPAdress>k__BackingField", IsRequired=true)]
        public string IPAdressk__BackingField {
            get {
                return this.IPAdressk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.IPAdressk__BackingFieldField, value) != true)) {
                    this.IPAdressk__BackingFieldField = value;
                    this.RaisePropertyChanged("IPAdressk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Port>k__BackingField", IsRequired=true)]
        public int Portk__BackingField {
            get {
                return this.Portk__BackingFieldField;
            }
            set {
                if ((this.Portk__BackingFieldField.Equals(value) != true)) {
                    this.Portk__BackingFieldField = value;
                    this.RaisePropertyChanged("Portk__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ClientWCFService.IClientConsoleCommunicator")]
    public interface IClientConsoleCommunicator {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientConsoleCommunicator/GetStatusInfos", ReplyAction="http://tempuri.org/IClientConsoleCommunicator/GetStatusInfosResponse")]
        HeuristicLab.Hive.Client.Console.ClientWCFService.StatusCommons GetStatusInfos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientConsoleCommunicator/GetConnection", ReplyAction="http://tempuri.org/IClientConsoleCommunicator/GetConnectionResponse")]
        HeuristicLab.Hive.Client.Console.ClientWCFService.ConnectionContainer GetConnection();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientConsoleCommunicator/SetConnection", ReplyAction="http://tempuri.org/IClientConsoleCommunicator/SetConnectionResponse")]
        void SetConnection(HeuristicLab.Hive.Client.Console.ClientWCFService.ConnectionContainer container);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IClientConsoleCommunicatorChannel : HeuristicLab.Hive.Client.Console.ClientWCFService.IClientConsoleCommunicator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ClientConsoleCommunicatorClient : System.ServiceModel.ClientBase<HeuristicLab.Hive.Client.Console.ClientWCFService.IClientConsoleCommunicator>, HeuristicLab.Hive.Client.Console.ClientWCFService.IClientConsoleCommunicator {
        
        public ClientConsoleCommunicatorClient() {
        }
        
        public ClientConsoleCommunicatorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClientConsoleCommunicatorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientConsoleCommunicatorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientConsoleCommunicatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HeuristicLab.Hive.Client.Console.ClientWCFService.StatusCommons GetStatusInfos() {
            return base.Channel.GetStatusInfos();
        }
        
        public HeuristicLab.Hive.Client.Console.ClientWCFService.ConnectionContainer GetConnection() {
            return base.Channel.GetConnection();
        }
        
        public void SetConnection(HeuristicLab.Hive.Client.Console.ClientWCFService.ConnectionContainer container) {
            base.Channel.SetConnection(container);
        }
    }
}
