//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.431
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeuristicLab.Problems.QuadraticAssignment.QAPInstanceService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QAPInstanceDto", Namespace="http://schemas.datacontract.org/2004/07/HeuristicLab.Services.ProblemInstances")]
    [System.SerializableAttribute()]
    public partial class QAPInstanceDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double BestKnownQualityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double[][] DistancesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasBestKnownQualityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool MaximizationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double[][] WeightsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double BestKnownQuality {
            get {
                return this.BestKnownQualityField;
            }
            set {
                if ((this.BestKnownQualityField.Equals(value) != true)) {
                    this.BestKnownQualityField = value;
                    this.RaisePropertyChanged("BestKnownQuality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double[][] Distances {
            get {
                return this.DistancesField;
            }
            set {
                if ((object.ReferenceEquals(this.DistancesField, value) != true)) {
                    this.DistancesField = value;
                    this.RaisePropertyChanged("Distances");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasBestKnownQuality {
            get {
                return this.HasBestKnownQualityField;
            }
            set {
                if ((this.HasBestKnownQualityField.Equals(value) != true)) {
                    this.HasBestKnownQualityField = value;
                    this.RaisePropertyChanged("HasBestKnownQuality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Maximization {
            get {
                return this.MaximizationField;
            }
            set {
                if ((this.MaximizationField.Equals(value) != true)) {
                    this.MaximizationField = value;
                    this.RaisePropertyChanged("Maximization");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double[][] Weights {
            get {
                return this.WeightsField;
            }
            set {
                if ((object.ReferenceEquals(this.WeightsField, value) != true)) {
                    this.WeightsField = value;
                    this.RaisePropertyChanged("Weights");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QAPSolutionDto", Namespace="http://schemas.datacontract.org/2004/07/HeuristicLab.Services.ProblemInstances")]
    [System.SerializableAttribute()]
    public partial class QAPSolutionDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] AssignmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AssignmentUndefinedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double QualityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] Assignment {
            get {
                return this.AssignmentField;
            }
            set {
                if ((object.ReferenceEquals(this.AssignmentField, value) != true)) {
                    this.AssignmentField = value;
                    this.RaisePropertyChanged("Assignment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AssignmentUndefined {
            get {
                return this.AssignmentUndefinedField;
            }
            set {
                if ((this.AssignmentUndefinedField.Equals(value) != true)) {
                    this.AssignmentUndefinedField = value;
                    this.RaisePropertyChanged("AssignmentUndefined");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Quality {
            get {
                return this.QualityField;
            }
            set {
                if ((this.QualityField.Equals(value) != true)) {
                    this.QualityField = value;
                    this.RaisePropertyChanged("Quality");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="QAPInstanceService.IQAP")]
    public interface IQAP {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQAP/GetProblemInstances", ReplyAction="http://tempuri.org/IQAP/GetProblemInstancesResponse")]
        string[] GetProblemInstances();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQAP/GetProblemInstanceData", ReplyAction="http://tempuri.org/IQAP/GetProblemInstanceDataResponse")]
        HeuristicLab.Problems.QuadraticAssignment.QAPInstanceService.QAPInstanceDto GetProblemInstanceData(string instance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQAP/GetBestSolutionsData", ReplyAction="http://tempuri.org/IQAP/GetBestSolutionsDataResponse")]
        HeuristicLab.Problems.QuadraticAssignment.QAPInstanceService.QAPSolutionDto[] GetBestSolutionsData(string instance);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IQAPChannel : HeuristicLab.Problems.QuadraticAssignment.QAPInstanceService.IQAP, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QAPClient : System.ServiceModel.ClientBase<HeuristicLab.Problems.QuadraticAssignment.QAPInstanceService.IQAP>, HeuristicLab.Problems.QuadraticAssignment.QAPInstanceService.IQAP {
        
        public QAPClient() {
        }
        
        public QAPClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QAPClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QAPClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QAPClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] GetProblemInstances() {
            return base.Channel.GetProblemInstances();
        }
        
        public HeuristicLab.Problems.QuadraticAssignment.QAPInstanceService.QAPInstanceDto GetProblemInstanceData(string instance) {
            return base.Channel.GetProblemInstanceData(instance);
        }
        
        public HeuristicLab.Problems.QuadraticAssignment.QAPInstanceService.QAPSolutionDto[] GetBestSolutionsData(string instance) {
            return base.Channel.GetBestSolutionsData(instance);
        }
    }
}
