//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersistenceCodeFix {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PersistenceCodeFix.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All StorableTypes should have a storable constructor.
        /// </summary>
        internal static string MissingStorableConstructorAnalyzerDescription {
            get {
                return ResourceManager.GetString("MissingStorableConstructorAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; has no storable constructor.
        /// </summary>
        internal static string MissingStorableConstructorAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("MissingStorableConstructorAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing storable constructor.
        /// </summary>
        internal static string MissingStorableConstructorAnalyzerTitle {
            get {
                return ResourceManager.GetString("MissingStorableConstructorAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All types should be marked with a StorableType attribute.
        /// </summary>
        internal static string MissingStorableTypeAnalyzerDescription {
            get {
                return ResourceManager.GetString("MissingStorableTypeAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; is not marked as StorableType.
        /// </summary>
        internal static string MissingStorableTypeAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("MissingStorableTypeAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing StorableType attribute.
        /// </summary>
        internal static string MissingStorableTypeAnalyzerTitle {
            get {
                return ResourceManager.GetString("MissingStorableTypeAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The StorableClass attribute is obsolete; Use the StorableType attribute instead.
        /// </summary>
        internal static string ObsoleteStorableClassAnalyzerDescription {
            get {
                return ResourceManager.GetString("ObsoleteStorableClassAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; should be marked as StorableType instead of StorableClass.
        /// </summary>
        internal static string ObsoleteStorableClassAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("ObsoleteStorableClassAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obsolete StorableClass attribute.
        /// </summary>
        internal static string ObsoleteStorableClassAnalyzerTitle {
            get {
                return ResourceManager.GetString("ObsoleteStorableClassAnalyzerTitle", resourceCulture);
            }
        }
    }
}
