ConfigMerger "%Outdir%HeuristicLab.PluginInfrastructure-3.3.dll.config" "HeuristicLab 3.3.exe.config"
ConfigMerger "%Outdir%HeuristicLab.Clients.Common-3.3.dll.config" "HeuristicLab 3.3.exe.config"
ConfigMerger "%Outdir%HeuristicLab.Optimizer-3.3.dll.config" "HeuristicLab 3.3.exe.config"
ConfigMerger "%Outdir%HeuristicLab.Persistence-3.3.dll.config" "HeuristicLab 3.3.exe.config"
ConfigMerger "%Outdir%HeuristicLab.Tracing-3.3.dll.config" "HeuristicLab 3.3.exe.config"