#region License Information
/* HeuristicLab
 * Copyright (C) 2002-2012 Heuristic and Evolutionary Algorithms Laboratory (HEAL)
 *
 * This file is part of HeuristicLab.
 *
 * HeuristicLab is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * HeuristicLab is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with HeuristicLab. If not, see <http://www.gnu.org/licenses/>.
 */
#endregion


using System;
using HeuristicLab.Data;
namespace HeuristicLab.Problems.Instances.DataAnalysis {
  public class Tower : IRealWorldRegressionDataDescriptor {
    public string Name { get { return "Tower"; } }
    public string Description {
      get {
        return "Publication: Order of Nonlinearity as a Complexity Measure for Models " +
               "Generated by Symbolic Regression via Pareto Genetic Programming" + Environment.NewLine +
               "Link: http://liinwww.ira.uka.de/cgi-bin/bibshow?e=Bj0hfofujd/qsphsbnnjoh/fyqboefe}24329837&r=bibtex&mode=intra";
      }
    }
    public IntRange Training { get { return new IntRange(0, 3135); } }
    public IntRange Test { get { return new IntRange(3135, 4999); } }
  }
}
